### ISSUE TITLE
How to run in debug mode outside k8s cluster ?

### ISSUE THREAD

**Issue by CrazyBBer** [micro/kubernetes#20]
did we had any official guide ? service need register to k8s and need to  talk to service inside k8s.

**Comment by asim** [comment]
There's no "debug" mode. We use the k8s registry https://github.com/micro/go-plugins/tree/master/registry/kubernetes. You can specify --registry_address and pass in the k8s api host which will then make calls via the api. This may not work for registering/deregistering since it expects to be in k8s do it it.
